
:experimental:

include::{partialsdir}/entities.adoc[]

[[appe-revision-history]]
= Revision History

Note that revision numbers relate to the edition of this manual, not to version numbers of {PRODUCT}.

`1.2`:: Thu Jun 25 2020, Petr Boko훾 (pbokoc@redhat.com)

* Update for CentOS 7.8.2003, based on the Red Hat Enterprise Linux 7.8 Installation Guide
* Added a chapter on Anaconda commands
* Singificant additions to the Quick Installation Guide chapter
* Various small improvements

`1.2`:: Thu Dec 5 2019, Petr Boko훾 (pbokoc@redhat.com)

* Update for CentOS 7.7.1908, based on the Red Hat Enterprise Linux 7.7 Installation Guide
* Removed the Composer chapter as it was moved from the original RHEL docs into a separate document
* Various small improvements

`1.1`:: Tue Nov 20 2018, Petr Boko훾 (pbokoc@redhat.com)

* Update for CentOS 7.6.1810, based on the Red Hat Enterprise Linux 7.6 Installation Guide
* Added NVDIMM support in Kickstart and GUI installer
* Added a chapter on Composer
* Added a Revision History

`1.0`:: Thu Oct 11 2018, Petr Boko훾 (pbokoc@redhat.com)

* Initial release of the new CentOS Installation Guide, based on Red Hat Enterprise Linux 7.5 Installation Guide and converted for the Antora toolchain
